
//*** Do not edit ****
//*** Automatically generated by make_version ***
 
const char *vstr = "ibp_server(no FIFO): v1.2.3p0\n"
             "Build Date: Thu Jul 23 10:24:52 CDT 2009\n"
             "Compiler: gcc (GCC) 4.2.4 (Ubuntu 4.2.4-1ubuntu4)\n"
             "Compile flags: -I./ceph -I/workspace/local/include -I/workspace/local/include/glib-2.0 -I/workspace/local/include -g -O2 -fPIC -Wall -I. -D_ENABLE_PHOEBUS -DHAVE_STDINT_H -D_ENABLE_DEBUG -D_HAS_XFS -D_LINUX64BIT -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -O2\n"
             "Build Host: alandepot1.reddnet.org\n"
             "Build OS: 2.6.24-24-server #1 SMP Wed Apr 15 15:41:09 UTC 2009 x86_64\n";        

const char *server_version() {
    return(vstr);
}

