
//*** Do not edit ****
//*** Automatically generated by make_version ***
 
const char *vstr = "ibp_server(no FIFO): v1.2.0p0\n"
             "Build Date: Thu Mar 26 15:24:30 CDT 2009\n"
             "Compiler: gcc (GCC) 4.2.4 (Ubuntu 4.2.4-1ubuntu3)\n"
             "Compile flags: -I./ceph -I/workspace/local/include -I/workspace/local/include/glib-2.0 -I/workspace/local/include -g -O2 -fPIC -Wall -I. -D_ENABLE_PHOEBUS -DHAVE_STDINT_H -D_ENABLE_DEBUG -D_HAS_XFS -D_LINUX64BIT -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -O2\n"
             "Build Host: alandepot1.reddnet.org\n"
             "Build OS: 2.6.24-23-server #1 SMP Thu Nov 27 18:45:02 UTC 2008 x86_64\n";        

const char *server_version() {
    return(vstr);
}

